# Generated by Django 5.1.2 on 2024-11-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='fileUrl',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
