# Generated by Django 5.1.2 on 2024-11-11 15:58

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_document_fileurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='fileUrl',
            field=models.FileField(storage=api.models.MyFileStorage(), upload_to='uploads/'),
        ),
    ]
