# Generated by Django 5.1.2 on 2024-11-11 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_document_fileurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='fileUrl',
        ),
    ]
