# Generated by Django 5.1.2 on 2024-11-12 07:33

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_document_fileurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='fileUrl',
            field=models.FileField(null=True, storage=api.models.MyFileStorage(), upload_to='uploads/'),
        ),
    ]
