# Generated by Django 5.1.2 on 2024-11-13 07:43

import api.models
import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_document_fileurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='id',
        ),
        migrations.AddField(
            model_name='document',
            name='fileId',
            field=models.CharField(default=api.models.get_uuid, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='fileUrl',
            field=models.FileField(null=True, storage=api.models.MyFileStorage(), upload_to='uploads/', validators=[api.validators.validate_file_extension]),
        ),
    ]
