# Generated by Django 5.1.2 on 2024-11-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_document_id_document_fileid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='fileId',
            field=models.CharField(default='5778513553', max_length=10, primary_key=True, serialize=False),
        ),
    ]
