# Generated by Django 5.1.2 on 2024-11-13 07:51

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_document_fileid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='fileId',
            field=models.CharField(max_length=10, primary_key=api.models.get_uuid, serialize=False),
        ),
    ]
