# Generated by Django 5.1.2 on 2024-11-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_document_fileid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='fileId',
        ),
        migrations.AddField(
            model_name='document',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
