# Generated by Django 5.1.2 on 2024-11-13 07:56

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_document_fileid_document_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='id',
        ),
        migrations.AddField(
            model_name='document',
            name='fileId',
            field=models.CharField(default=api.models.get_uuid, max_length=10, primary_key=True, serialize=False),
        ),
    ]
