# Generated by Django 5.1.2 on 2024-11-13 08:34

import api.models
import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_document_id_document_fileid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='fileUrl',
            field=models.FileField(null=True, storage=api.models.MyFileStorage(), upload_to='uploads/', validators=[api.validators.validate_file_extension, api.validators.validate_file_size]),
        ),
    ]
